// Code generated by mockery v1.0.0. DO NOT EDIT.

package render

import context "context"
import grid "github.com/slok/grafterm/internal/view/grid"
import mock "github.com/stretchr/testify/mock"
import render "github.com/slok/grafterm/internal/view/render"

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Renderer) Close() {
	_m.Called()
}

// LoadDashboard provides a mock function with given fields: ctx, _a1
func (_m *Renderer) LoadDashboard(ctx context.Context, _a1 *grid.Grid) ([]render.Widget, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []render.Widget
	if rf, ok := ret.Get(0).(func(context.Context, *grid.Grid) []render.Widget); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]render.Widget)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *grid.Grid) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
