// Code generated by mockery v1.0.0. DO NOT EDIT.

package render

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/slok/grafterm/internal/model"
import render "github.com/slok/grafterm/internal/view/render"

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Renderer) Close() {
	_m.Called()
}

// LoadDashboard provides a mock function with given fields: ctx, dashboard
func (_m *Renderer) LoadDashboard(ctx context.Context, dashboard model.Dashboard) ([]render.Widget, error) {
	ret := _m.Called(ctx, dashboard)

	var r0 []render.Widget
	if rf, ok := ret.Get(0).(func(context.Context, model.Dashboard) []render.Widget); ok {
		r0 = rf(ctx, dashboard)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]render.Widget)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Dashboard) error); ok {
		r1 = rf(ctx, dashboard)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
