// Code generated by mockery v1.0.0. DO NOT EDIT.

package render

import mock "github.com/stretchr/testify/mock"
import model "github.com/slok/grafterm/internal/model"

// SinglestatWidget is an autogenerated mock type for the SinglestatWidget type
type SinglestatWidget struct {
	mock.Mock
}

// GetWidgetCfg provides a mock function with given fields:
func (_m *SinglestatWidget) GetWidgetCfg() model.Widget {
	ret := _m.Called()

	var r0 model.Widget
	if rf, ok := ret.Get(0).(func() model.Widget); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.Widget)
	}

	return r0
}

// SetColor provides a mock function with given fields: hexColor
func (_m *SinglestatWidget) SetColor(hexColor string) error {
	ret := _m.Called(hexColor)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(hexColor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sync provides a mock function with given fields: value
func (_m *SinglestatWidget) Sync(value float64) error {
	ret := _m.Called(value)

	var r0 error
	if rf, ok := ret.Get(0).(func(float64) error); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
